server:
  servlet:
    encoding:
      force-response: true

    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:../../db/em.db

  messages:
      basename: "messages,errors"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

