server:
  servlet:
    encoding:
      force-response: true

    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/main/resources/database/em.db

  messages:
      basename: "messages,errors"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

hospital:
  api:
    host: http://127.0.0.1:8000